"""Writes P2lNative.cs, the C# P/Invoke declarations of every function in include/p2l_runtime.h, for Unity and
.NET hosts. Run it after changing the header:  python generate.py  (from this folder). MIT License."""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
HEADER = os.path.join(HERE, '..', '..', 'include', 'p2l_runtime.h')

# Pointer parameters that carry several values (or text to pass in) rather than one result.
ARRAYS = {'out', 'samples', 'transform', 'multiply', 'screen', 'rgba', 'bytes', 'error', 'id', 'role'}


KEYWORDS = {'out', 'in', 'ref', 'params', 'base', 'object', 'string', 'event', 'fixed', 'lock', 'operator', 'checked'}


def parameter(declaration):
    declaration = declaration.strip()
    name = re.findall(r'(\w+)$', declaration)[0]
    text = parameter_of(declaration, name)
    return text if name not in KEYWORDS else text[:-len(name)] + '@' + name


def parameter_of(declaration, name):
    kind = re.sub(r'\s+', ' ', declaration[:-len(name)]).replace(' *', '*').strip()
    kind = kind.replace('const ', '')
    if kind in ('P2lRig*', 'P2lModel*'):
        return 'IntPtr ' + name
    if kind == 'char**' or kind == 'uint8_t**':
        return 'out IntPtr ' + name
    if kind == 'uint8_t*':
        return ('byte[] ' if name != 'pointer' else 'IntPtr ') + name
    if kind == 'char*':
        return 'byte[] ' + name
    scalar = {'uint32_t': 'uint', 'int32_t': 'int', 'float': 'float', 'size_t': 'UIntPtr', 'bool': 'bool'}
    if kind.endswith('*'):
        base = scalar[kind[:-1]]
        if name in ARRAYS:
            return base + '[] ' + name
        if base == 'bool':
            return '[MarshalAs(UnmanagedType.I1)] out bool ' + name
        return 'out ' + base + ' ' + name
    if kind == 'bool':
        return '[MarshalAs(UnmanagedType.I1)] bool ' + name
    return scalar[kind] + ' ' + name


def returns(kind):
    kind = re.sub(r'\s+', ' ', kind).replace(' *', '*').replace('const ', '').strip()
    if kind.endswith('*'):
        return [], 'IntPtr'
    if kind == 'bool':
        return ['[return: MarshalAs(UnmanagedType.I1)]'], 'bool'
    return [], {'void': 'void', 'uint32_t': 'uint', 'int32_t': 'int', 'float': 'float'}[kind]


def main():
    text = open(HEADER, encoding='utf-8').read()
    defines = re.findall(r'^#define (P2L_\w+) (\d+)u?$', text, flags=re.M)
    body = re.sub(r'/\*.*?\*/', '', text, flags=re.S)
    body = '\n'.join(l for l in body.splitlines() if not l.lstrip().startswith('#'))
    functions = re.findall(r'([A-Za-z_][\w \*]*?)\b(p2l_\w+)\s*\(([^)]*)\)\s*;', body, flags=re.S)
    out = ['// Generated by generate.py from include/p2l_runtime.h; do not edit. MIT License.',
           '// The C ABI as declared there: rigs and models are IntPtr handles, returned strings and arrays IntPtr',
           '// (read them with P2l.Utf8 and Marshal.Copy), text passed in is null-terminated UTF-8 (P2l.Text).',
           'using System;', 'using System.Runtime.InteropServices;', '', 'namespace PSD2Live.Runtime', '{',
           '    public static class P2lNative', '    {',
           '        /// <summary>The runtime library: p2l_runtime.dll, libp2l_runtime.so or .dylib.</summary>',
           '        public const string Library = "p2l_runtime";', '']
    for name, value in defines:
        out.append('        public const uint %s = %s;' % (name[4:], value))
    out.append('')
    for kind, name, args in functions:
        attributes, result = returns(kind)
        args = args.strip()
        parameters = [] if args in ('', 'void') else [parameter(a) for a in args.split(',')]
        out.append('        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]')
        out.extend('        ' + a for a in attributes)
        out.append('        public static extern %s %s(%s);' % (result, name, ', '.join(parameters)))
    out += ['    }', '}', '']
    open(os.path.join(HERE, 'P2lNative.cs'), 'w', encoding='utf-8', newline='\n').write('\n'.join(out))
    print('%d functions, %d constants' % (len(functions), len(defines)))


main()
