// Generated by generate.py from include/p2l_runtime.h; do not edit. MIT License.
// The C ABI as declared there: rigs and models are IntPtr handles, returned strings and arrays IntPtr
// (read them with P2l.Utf8 and Marshal.Copy), text passed in is null-terminated UTF-8 (P2l.Text).
using System;
using System.Runtime.InteropServices;

namespace PSD2Live.Runtime
{
    public static class P2lNative
    {
        /// <summary>The runtime library: p2l_runtime.dll, libp2l_runtime.so or .dylib.</summary>
        public const string Library = "p2l_runtime";

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void P2lLog(int level, IntPtr message, IntPtr user);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate IntPtr P2lAllocate(UIntPtr size, UIntPtr align, IntPtr user);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void P2lFree(IntPtr pointer, UIntPtr size, UIntPtr align, IntPtr user);
        // Keep a delegate given to the runtime alive (in a static field) for as long as the runtime may call it.

        public const uint ABI_VERSION_MAJOR = 1;
        public const uint ABI_VERSION_MINOR = 4;
        public const uint LOG_ERROR = 0;
        public const uint LOG_WARNING = 1;
        public const uint LOAD_VERIFY_CRC = 1;
        public const uint PARAMETER_REPEAT = 1;
        public const uint PARAMETER_BLEND_SHAPE = 2;
        public const uint STAGE_CLIPS = 1;
        public const uint STAGE_EXPRESSIONS = 2;
        public const uint STAGE_BEHAVIORS = 4;
        public const uint STAGE_POSES = 8;
        public const uint STAGE_PHYSICS = 16;
        public const uint STAGE_SIM = 32;
        public const uint STAGE_ALL = 63;
        public const uint BLINK = 1;
        public const uint BREATH = 2;
        public const uint LOOK = 4;
        public const uint LIP_SYNC = 8;
        public const uint MAX_LAYERS = 16;
        public const uint BLEND_NORMAL = 0;
        public const uint BLEND_CUBISM_ADD = 1;
        public const uint BLEND_CUBISM_MULTIPLY = 2;
        public const uint BLEND_ADD = 3;
        public const uint BLEND_ADD_GLOW = 4;
        public const uint BLEND_DARKEN = 5;
        public const uint BLEND_MULTIPLY = 6;
        public const uint BLEND_COLOR_BURN = 7;
        public const uint BLEND_LINEAR_BURN = 8;
        public const uint BLEND_LIGHTEN = 9;
        public const uint BLEND_SCREEN = 10;
        public const uint BLEND_COLOR_DODGE = 11;
        public const uint BLEND_OVERLAY = 12;
        public const uint BLEND_SOFT_LIGHT = 13;
        public const uint BLEND_HARD_LIGHT = 14;
        public const uint BLEND_LINEAR_LIGHT = 15;
        public const uint BLEND_HUE = 16;
        public const uint BLEND_COLOR = 17;
        public const uint ALPHA_OVER = 0;
        public const uint ALPHA_ATOP = 1;
        public const uint ALPHA_OUT = 2;
        public const uint ALPHA_CONJOINT_OVER = 3;
        public const uint ALPHA_DISJOINT_OVER = 4;
        public const uint MESH_VISIBLE = 1;
        public const uint MESH_VISIBILITY_CHANGED = 2;
        public const uint MESH_OPACITY_CHANGED = 4;
        public const uint MESH_DRAW_ORDER_CHANGED = 8;
        public const uint MESH_RENDER_ORDER_CHANGED = 16;
        public const uint MESH_VERTICES_CHANGED = 32;
        public const uint MESH_COLORS_CHANGED = 64;
        public const uint PART_VISIBLE = 1;
        public const uint PART_SKETCH = 2;
        public const uint GROUP_PASS_THROUGH = 0;
        public const uint GROUP_SORTED = 1;
        public const uint GROUP_ISOLATED = 2;
        public const uint SKIN = 1;
        public const uint EXACT_LINKS = 2;
        public const uint SIM = 4;
        public const uint COLLISION = 8;
        public const uint RENDER_STRAIGHT = 1;
        public const uint RENDER_KEEP = 2;

        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_abi_version();
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_set_log(P2lLog log, IntPtr user);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        public static extern bool p2l_set_allocator(P2lAllocate allocate, P2lFree free, IntPtr user);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_rig_load(byte[] bytes, UIntPtr len, byte[] error, UIntPtr error_capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_rig_load_ex(byte[] bytes, UIntPtr len, uint flags, byte[] error, UIntPtr error_capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_model_load(byte[] bytes, UIntPtr len, uint flags, byte[] error, UIntPtr error_capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_model_free(IntPtr model);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_rig_create(IntPtr model, byte[] error, UIntPtr error_capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_format_support();
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_rig_free(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_rig_failure(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_version();
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_canvas(IntPtr rig, out float width, out float height);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_canvas_origin(IntPtr rig, out float x, out float y, out float pixels_per_unit);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_parameter_count(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_parameter_id(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_parameter_name(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int p2l_parameter_index(IntPtr rig, byte[] id);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        public static extern bool p2l_parameter_range(IntPtr rig, uint index, out float min, out float max, out float default_value);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_parameter_flags(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_parameter_snaps(IntPtr rig, uint index, float[] @out, uint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_parameter_values(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_parameter_current(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_set_parameter(IntPtr rig, uint index, float value);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        public static extern bool p2l_set_parameter_override(IntPtr rig, uint index, float value, float weight);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_clear_parameter_overrides(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_role_parameters(IntPtr rig, byte[] role, uint[] @out, uint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_gui_joysticks(IntPtr rig, uint[] @out, uint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_gui_node_count(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        public static extern bool p2l_gui_node(IntPtr rig, uint index, out int parameter, out uint children, [MarshalAs(UnmanagedType.I1)] out bool open);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_gui_node_id(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_gui_node_name(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int p2l_gui_node_label(IntPtr rig, uint index, out IntPtr preset, out uint argb);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_evaluate(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_update(IntPtr rig, float dt);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_update_stages(IntPtr rig, float dt, uint stages);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_physics_reset(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_physics_wind(IntPtr rig, float x, float y);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_physics_stabilize(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_set_opacity(IntPtr rig, float opacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float p2l_opacity(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        public static extern bool p2l_set_mesh_colors(IntPtr rig, uint index, float[] multiply, float[] screen);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        public static extern bool p2l_set_part_colors(IntPtr rig, uint index, float[] multiply, float[] screen);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_behaviors(IntPtr rig, uint flags);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_behavior_seed(IntPtr rig, uint seed);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        public static extern bool p2l_blink_settings(IntPtr rig, float interval_min, float interval_max, float closing, float closed, float opening);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        public static extern bool p2l_behavior_strength(IntPtr rig, float sway, float look, float look_speed);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float p2l_lip_sync_samples(IntPtr rig, float[] samples, UIntPtr count, float gain);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_look_at(IntPtr rig, float x, float y);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_lip_sync(IntPtr rig, float level);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_clip_count(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_clip_id(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_clip_name(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_clip_group(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        public static extern bool p2l_clip_info(IntPtr rig, uint index, out float duration, out float fps, [MarshalAs(UnmanagedType.I1)] out bool looping, out float fade_in, out float fade_out);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_play(IntPtr rig, int index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int p2l_clip_playing(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float p2l_clip_time(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_clip_seek(IntPtr rig, float time);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        public static extern bool p2l_clip_finished(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        public static extern bool p2l_play_layer(IntPtr rig, uint layer, int index, uint priority);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        public static extern bool p2l_set_layer_weight(IntPtr rig, uint layer, float weight);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        public static extern bool p2l_layer_state(IntPtr rig, uint layer, out int clip, out float time, out uint priority, [MarshalAs(UnmanagedType.I1)] out bool finished);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_layer_seek(IntPtr rig, uint layer, float time);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_event_count(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_event(IntPtr rig, uint index, out uint layer, out int clip, out float time);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_mesh_count(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_mesh_id(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_mesh_name(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_mesh_vertex_count(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_mesh_uvs(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_mesh_indices(IntPtr rig, uint index, out uint count);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int p2l_mesh_texture(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int p2l_mesh_blend(IntPtr rig, uint index, [MarshalAs(UnmanagedType.I1)] out bool culling);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int p2l_mesh_alpha_blend(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int p2l_mesh_part(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_mesh_masks(IntPtr rig, uint index, uint[] @out, uint capacity, [MarshalAs(UnmanagedType.I1)] out bool inverted);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_mesh_vertices(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float p2l_mesh_opacity(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float p2l_mesh_draw_order(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_mesh_colors(IntPtr rig, uint index, float[] multiply, float[] screen);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_mesh_changes(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_render_order(IntPtr rig, uint[] @out, uint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_render_commands(IntPtr rig, int[] @out, uint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_part_count(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_part_id(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_part_name(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int p2l_part_parent(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_part_flags(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int p2l_part_group(IntPtr rig, uint index, out int blend, out int alpha_blend, [MarshalAs(UnmanagedType.I1)] out bool invert_mask);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_part_masks(IntPtr rig, uint index, uint[] @out, uint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        public static extern bool p2l_part_composite(IntPtr rig, uint index, out float opacity, float[] multiply, float[] screen);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float p2l_part_opacity(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        public static extern bool p2l_set_part_opacity(IntPtr rig, uint index, float opacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_advanced_available(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_set_advanced(IntPtr rig, uint features);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_sim_reset(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_sim_wind(IntPtr rig, float x, float y);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_sim_colliders(IntPtr rig, float[] @out, uint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_bone_count(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_bone_id(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        public static extern bool p2l_bone_transform(IntPtr rig, uint index, float[] @out);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_expression_count(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_expression_id(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_expression_name(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_expression(IntPtr rig, int index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        public static extern bool p2l_expression_add(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        public static extern bool p2l_expression_remove(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_expressions_playing(IntPtr rig, uint[] @out, uint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_hit_area_count(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_hit_area_id(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_hit_area_name(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int p2l_hit_test(IntPtr rig, float x, float y);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_hit_area_meshes(IntPtr rig, uint index, uint[] @out, uint capacity);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_pose_group_count(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_pose_group_size(IntPtr rig, uint group);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        public static extern bool p2l_pose_show(IntPtr rig, uint group, uint entry);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int p2l_pose_shown(IntPtr rig, uint group);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_mesh_user_data(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_meta_count(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_meta_key(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_meta_value(IntPtr rig, uint index);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_alloc(UIntPtr len);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void p2l_dealloc(IntPtr pointer, UIntPtr len);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        public static extern bool p2l_render(IntPtr rig, byte[] rgba, uint width, uint height, float[] transform, uint flags);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.I1)]
        public static extern bool p2l_render_texture(IntPtr rig, uint page, byte[] rgba, uint width, uint height);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern uint p2l_texture_count(IntPtr rig);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_texture_png(IntPtr rig, uint index, out UIntPtr len, out uint width, out uint height);
        [DllImport(Library, CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern IntPtr p2l_texture_info(IntPtr rig, uint index, out int kind, out uint width, out uint height, out IntPtr data, out UIntPtr len);
    }
}
