package io.github.psd2live.core

import io.github.psd2live.targets.cubism.PuppetIr
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.umamo.edit.withDrawablesDeleted
import org.umamo.format.art.SourceArt
import org.umamo.runtime.model.DrawableId
import org.umamo.runtime.model.PuppetModel

/**
 * Where an edit changes what the generators make under the journal, the journal is not replayed on the new output:
 * the previous generated rig G, the new one G' and the authored rig M merge ([RigRegeneration]) and the result is
 * stored as a `rig_checkpoint` ([RigCheckpoint]) where the previous journal ends, before the entries the edit adds.
 * Replay then starts there; the entries before it stay as history.
 *
 * After a generation migration the authored rig's meshes hang from renamed copies of the generated deformers
 * ([RigGenerationFrames]); G and G' merge under those names ([RigGenerationFrames.named]), or every mesh would read as
 * one the user re-parented and keep its old place. The checkpoint stores the generation as the generators made it.
 */
internal object RigRegenerationCheckpoint {
	/**
	 * [next] - a configuration whose edits continue [current]'s ([RigEditOverlay.continues]) - with a checkpoint where
	 * [current]'s journal ends, when the generated rig of [source] under [next], as that journal sees it, differs from
	 * [current]'s. Null when it does not: replaying the journal gives what it gave.
	 *
	 * G is [current]'s base as this build generates it, so what a newer generator would make differently for objects
	 * the user left counts as the user's and stays: generator improvements arrive only through [updated].
	 */
	fun checkpointed(pipeline: PSD2LivePipeline, current: RigPreviewModel, next: PipelineConfig, source: SourceArt,
	                 checkpoint: () -> Unit = {}): PipelineConfig? {
		val before = current.config.rigEdits
		val after = next.rigEdits
		val boundary = before.authoringJournal.size
		// The edit checkpointed already (a preset that switched the generation itself).
		if (after.authoringJournal.subList(boundary, after.authoringJournal.size).any(RigCheckpoint::isRecord)) return null
		val (base, bindingKey) = pipeline.generatedBaseOf(source, next)
		if (current.sources.baseKnown && base === current.baseRig) return null
		checkpoint()
		// The new generation as the entries up to the boundary see it: later splits' parts not yet in place.
		val records = after.authoringJournal.subList(0, boundary)
		val (previous, seen) = withV1Parts(current.baseRig.resolvedPuppet().reboundTo(base.puppet.atlas, base.puppet.sources),
			current.baseRig.primitiveSkins, base.resolvedPuppet(records.filter(ArtPrimitiveV2::isV2)), base.primitiveSkins, records)
		if (PuppetIr.toIr(previous) == PuppetIr.toIr(seen)) return null
		checkpoint()
		val record = merged(RigGenerationFrames.named(previous, records), RigGenerationFrames.named(seen, records), current.authored, base,
			bindingKey, seen, checkpoint).record
		val journal = ArrayList<JsonObject>(after.authoringJournal).apply { add(boundary, record) }
		return next.copy(rigEdits = after.copy(authoringJournal = journal))
	}

	/** A regeneration with this build's generators: the new configuration and what its merge reported. */
	class Update(val config: PipelineConfig, val issues: List<RigRegeneration.Issue>)

	/**
	 * [current]'s document regenerated by this build's generators: the generated rig its last checkpoint stores (what
	 * the generators made then), the one they make now for the same input and the authored rig merge, and the result
	 * is checkpointed at the end of the journal. Null when the journal has no checkpoint storing its generated rig (a
	 * document without one is generated by this build on every build already) or the generators make the same rig.
	 */
	fun updated(pipeline: PSD2LivePipeline, current: RigPreviewModel, source: SourceArt, checkpoint: () -> Unit = {}): Update? {
		val overlay = current.config.rigEdits
		val index = overlay.checkpointIndex.takeIf { it >= 0 } ?: return null
		val journal = overlay.authoringJournal
		val stored = RigCheckpoint.generated(journal[index]) ?: return null
		val (base, bindingKey) = pipeline.generatedBaseOf(source, current.config)
		checkpoint()
		val atlas = base.puppet.atlas; val sources = base.puppet.sources
		// The stored generated rig holds the version 1 parts its checkpoint merged; their skins now come from the base.
		val (previous, now) = withV1Parts(stored.authored.rig.puppet.reboundTo(atlas, sources), PrimitiveSkins.None,
			base.resolvedPuppet(journal.subList(0, index).filter(ArtPrimitiveV2::isV2)), base.primitiveSkins, journal.subList(0, index),
			replayOnPrevious = false)
		if (PuppetIr.toIr(previous) == PuppetIr.toIr(now)) return null
		checkpoint()
		val merged = merged(RigGenerationFrames.named(previous, journal), RigGenerationFrames.named(now, journal), current.authored, base, bindingKey,
			base.resolvedPuppet(journal.filter(ArtPrimitiveV2::isV2)), checkpoint)
		return Update(current.config.copy(rigEdits = overlay.copy(authoringJournal = journal + merged.record)), merged.issues)
	}

	/**
	 * [previous] and [next] with the parts of the version 1 splits among [journal]'s entries in place, journal order.
	 * Such a part comes from its record, not from the generators, so a resolved rig never has it; the merge kept the
	 * authored part as the user's, and the skin and welds the skeleton bake gave it ([PrimitiveSkins]) never arrived.
	 * A record whose parts the skeleton skins on either side ([previousSkins], [nextSkins]) or [previous] holds already
	 * (a stored generated rig) replays on both as the journal replays it - on [previous] only where it lacks the parts,
	 * and not at all there when [replayOnPrevious] is false. One that does not replay leaves its parts out of both, so
	 * they stay the user's.
	 */
	private fun withV1Parts(previous: PuppetModel, previousSkins: PrimitiveSkins, next: PuppetModel, nextSkins: PrimitiveSkins,
	                        journal: List<JsonObject>, replayOnPrevious: Boolean = true): Pair<PuppetModel, PuppetModel> {
		var g = previous
		var g2 = next
		for (record in journal) {
			if (!ArtPrimitiveJournal.isRecord(record) || ArtPrimitiveV2.isV2(record)) continue
			val ids = ArtPrimitiveJournal.primitives(record).mapTo(HashSet()) { DrawableId(it.getValue("id").jsonPrimitive.content) }
			val held = g.drawables.any { it.id in ids }
			if (!held && (!replayOnPrevious || ids.none { it in previousSkins.drawables || it in nextSkins.drawables })) continue
			try {
				val replayed = if (held) g else ArtPrimitiveJournal.replay(g, record, previousSkins)
				g2 = ArtPrimitiveJournal.replay(g2, record, nextSkins)
				g = replayed
			} catch (failure: java.util.concurrent.CancellationException) {
				throw failure
			} catch (failure: RuntimeException) {
				g = g.withDrawablesDeleted(ids)
			}
		}
		return g to g2
	}

	private class Merged(val record: JsonObject, val issues: List<RigRegeneration.Issue>)

	/**
	 * The checkpoint of [authored] merged from [previous] onto [next], bound to [base]'s atlas; [generated] is stored as
	 * the generation the checkpoint was made from.
	 */
	private fun merged(previous: PuppetModel, next: PuppetModel, authored: AuthoredRig, base: BuiltRig, bindingKey: String,
	                   generated: PuppetModel, checkpoint: () -> Unit): Merged {
		val result = RigRegeneration.merge(previous, next, authored.rig.puppet.reboundTo(base.puppet.atlas, base.puppet.sources), checkpoint)
		val model = result.model
		val ids = model.drawables.mapTo(HashSet()) { it.id.raw }
		fun <V> joined(generatedMap: Map<String, V>, user: Map<String, V>) = (user + generatedMap).filterKeys { it in ids }
		val rig = base.copy(puppet = model,
			layerIdByDrawableId = joined(base.layerIdByDrawableId, authored.rig.layerIdByDrawableId),
			sourceBoundsByDrawableId = joined(base.sourceBoundsByDrawableId, authored.rig.sourceBoundsByDrawableId),
			pageByDrawableId = model.drawables.filter { it.id.raw in base.pageByDrawableId || it.id.raw in authored.rig.pageByDrawableId }
				.associate { it.id.raw to it.texturePage },
			supersededEntryNotes = authored.rig.supersededEntryNotes, overrideIssues = emptyList())
		val record = RigCheckpoint.encode(AuthoredRig(rig, authored.visibilityTargets.filter { it.first in ids }), bindingKey, result.issues,
			generated = AuthoredRig(base.copy(puppet = generated), emptyList()))
		return Merged(record, result.issues)
	}
}
